/**
 * Generates Kotlin Activity/Fragment code from a list of [ViewBean].
 *
 * Produces:
 * - Package declaration and imports
 * - View field declarations (findViewById or ViewBinding style)
 * - onCreate / onCreateView boilerplate
 * - Click listener setup for widgets that have `clickable` set
 * - View initialization with property assignments
 *
 * Based on Sketchware-IA's code generation pipeline and AndroidIDE's
 * IToolingApiServer approach.
 */
package com.xcoder.visual.codegen

import com.xcoder.visual.model.*

/** Configuration for Kotlin code generation. */
data class KotlinGenConfig(
    /** Package name for the generated class. */
    val packageName: String = "com.xcoder.app",
    /** Class name (Activity or Fragment). */
    val className: String = "MainActivity",
    /** Layout resource name (without R.layout. prefix). */
    val layoutName: String = "activity_main",
    /** Generate as Fragment instead of Activity. */
    val isFragment: Boolean = false,
    /** Use ViewBinding instead of findViewById. */
    val useViewBinding: Boolean = false,
    /** ViewBinding class name (e.g. "ActivityMainBinding"). */
    val viewBindingClassName: String = "ActivityMainBinding",
    /** Include coroutines lifecycle scope. */
    val useCoroutines: Boolean = true,
    /** Extra import statements. */
    val extraImports: Set<String> = emptySet()
)

class KotlinGenerator(private val config: KotlinGenConfig = KotlinGenConfig()) {

    private val imports = mutableSetOf<String>()
    private val fieldDeclarations = mutableListOf<String>()
    private val initStatements = mutableListOf<String>()
    private val clickListeners = mutableListOf<String>()
    private val lifecycleMethods = mutableListOf<String>()

    /**
     * Generate a complete Kotlin source file from the given [views].
     *
     * @param views flat list of [ViewBean] (parent relationships are used for hierarchy)
     * @return generated Kotlin source code
     */
    fun generate(views: List<ViewBean>): String {
        reset()
        collectImports(views)
        generateFields(views)
        generateInitialization(views)
        generateClickListeners(views)

        return buildString {
            append("package ${config.packageName}\n\n")
            append("// Generated by XCoder IDE Visual Editor\n")
            append("// Do not edit manually — changes will be overwritten.\n\n")

            // Imports
            val sortedImports = imports.toSortedSet()
            for (imp in sortedImports) {
                append("import $imp\n")
            }
            append("\n")

            // Class declaration
            val superClass = if (config.isFragment) "Fragment()" else "AppCompatActivity()"
            append("class ${config.className} : $superClass {\n\n")

            // Fields
            if (fieldDeclarations.isNotEmpty()) {
                for (field in fieldDeclarations) {
                    append("    $field\n")
                }
                append("\n")
            }

            // onCreate or onCreateView
            if (config.isFragment) {
                appendFragmentMethods()
            } else {
                appendActivityMethods()
            }

            // Click listeners
            if (clickListeners.isNotEmpty()) {
                append("    // ── Click Listeners ────────────────────────────────────\n")
                for (listener in clickListeners) {
                    append("    $listener\n\n")
                }
            }

            // Extra lifecycle methods
            for (method in lifecycleMethods) {
                append("    $method\n\n")
            }

            append("}\n")
        }
    }

    // ── Activity generation ───────────────────────────────────────────

    private fun StringBuilder.appendActivityMethods() {
        val bindingSetup = if (config.useViewBinding) {
            "        val binding = ${config.viewBindingClassName}.inflate(layoutInflater)\n" +
                    "        setContentView(binding.root)\n"
        } else {
            "        setContentView(R.layout.${config.layoutName})\n"
        }

        append("    override fun onCreate(savedInstanceState: android.os.Bundle?) {\n")
        append("        super.onCreate(savedInstanceState)\n")
        append(bindingSetup)
        append("\n")

        // View initializations
        if (initStatements.isNotEmpty()) {
            append("        // Initialize views\n")
            for (stmt in initStatements) {
                append("        $stmt\n")
            }
            append("\n")
        }

        // Set up click listeners
        if (clickListeners.isNotEmpty()) {
            append("        // Set up click listeners\n")
            for (i in clickListeners.indices) {
                append("        setupClickListener${i}()\n")
            }
            append("\n")
        }

        append("    }\n\n")
    }

    // ── Fragment generation ───────────────────────────────────────────

    private fun StringBuilder.appendFragmentMethods() {
        val bindingSetup = if (config.useViewBinding) {
            "        val binding = ${config.viewBindingClassName}.inflate(inflater, container, false)\n" +
                    "        return binding.root\n"
        } else {
            "        return inflater.inflate(R.layout.${config.layoutName}, container, false)\n"
        }

        append("    override fun onCreateView(\n")
        append("        inflater: android.view.LayoutInflater,\n")
        append("        container: android.view.ViewGroup?,\n")
        append("        savedInstanceState: android.os.Bundle?\n")
        append("    ): android.view.View? {\n")
        append(bindingSetup)
        append("    }\n\n")

        append("    override fun onViewCreated(view: android.view.View, savedInstanceState: android.os.Bundle?) {\n")
        append("        super.onViewCreated(view, savedInstanceState)\n\n")

        if (initStatements.isNotEmpty()) {
            append("        // Initialize views\n")
            for (stmt in initStatements) {
                append("        $stmt\n")
            }
            append("\n")
        }

        if (clickListeners.isNotEmpty()) {
            append("        // Set up click listeners\n")
            for (i in clickListeners.indices) {
                append("        setupClickListener${i}()\n")
            }
            append("\n")
        }

        append("    }\n\n")
    }

    // ── Collection / analysis ─────────────────────────────────────────

    private fun collectImports(views: List<ViewBean>) {
        if (config.isFragment) {
            imports.add("android.os.Bundle")
            imports.add("android.view.LayoutInflater")
            imports.add("android.view.View")
            imports.add("android.view.ViewGroup")
            imports.add("androidx.fragment.app.Fragment")
        } else {
            imports.add("android.os.Bundle")
            imports.add("androidx.appcompat.app.AppCompatActivity")
        }

        for (view in views) {
            val info = view.buildClassInfo()
            if (info.needsImport) {
                imports.add(info.importStatement)
            }
            // Import types used in property setters
            if (view.isTextWidget && view.text.maxLines != Integer.MAX_VALUE) {
                // android.text.TextUtils.TruncateAt is often needed
            }
            if (view.clickable) {
                imports.add("android.view.View")
            }
        }

        if (config.useCoroutines) {
            imports.add("androidx.lifecycle.lifecycleScope")
            imports.add("kotlinx.coroutines.launch")
        }

        imports.addAll(config.extraImports)
    }

    private fun generateFields(views: List<ViewBean>) {
        for (view in views) {
            if (view.id.isBlank()) continue
            val safeId = safeKotlinId(view.id)
            val typeName = view.simpleClassName
            if (config.useViewBinding) {
                fieldDeclarations.add("private lateinit var binding: ${config.viewBindingClassName}")
                // Only add one binding field
                if (fieldDeclarations.any { it.contains("lateinit var binding") }) {
                    fieldDeclarations.removeAt(fieldDeclarations.lastIndex)
                    if (!fieldDeclarations.any { it.contains("lateinit var binding") }) {
                        fieldDeclarations.add("private lateinit var binding: ${config.viewBindingClassName}")
                    }
                }
            } else {
                fieldDeclarations.add("private lateinit var $safeId: $typeName")
            }
        }
        // Deduplicate
        val seen = mutableSetOf<String>()
        val deduped = mutableListOf<String>()
        for (f in fieldDeclarations) {
            if (seen.add(f)) deduped.add(f)
        }
        fieldDeclarations.clear()
        fieldDeclarations.addAll(deduped)
    }

    private fun generateInitialization(views: List<ViewBean>) {
        for (view in views) {
            if (view.id.isBlank()) continue
            val safeId = safeKotlinId(view.id)

            if (!config.useViewBinding) {
                // findViewById
                val cast = view.simpleClassName
                initStatements.add("$safeId = findViewById(R.id.${view.id})")
            }

            // Text properties
            if (view.isTextWidget && view.text.text.isNotEmpty()) {
                initStatements.add("$safeId.text = \"${escapeKotlin(view.text.text)}\"")
            }
            if (view.isTextWidget && view.text.textSize != 14f) {
                initStatements.add("$safeId.textSize = ${view.text.textSize}f")
            }
            if (view.isTextWidget && view.text.textColor != 0xFF000000.toInt()) {
                val color = "0x${view.text.textColor.toUInt().toString(16).uppercase()}"
                initStatements.add("$safeId.setTextColor($color.toInt())")
            }
            if (view.isTextWidget && view.text.hint.isNotEmpty()) {
                initStatements.add("$safeId.hint = \"${escapeKotlin(view.text.hint)}\"")
            }

            // Image properties
            if (view.isImageWidget && view.image.src.isNotEmpty()) {
                val resName = view.image.src
                if (resName.startsWith("@mipmap/") || resName.startsWith("@drawable/")) {
                    initStatements.add("$safeId.setImageResource(R.${resName.removePrefix("@")})")
                }
            }

            // Alpha
            if (view.alpha != 1f) {
                initStatements.add("$safeId.alpha = ${view.alpha}f")
            }

            // Enabled
            if (!view.enabled) {
                initStatements.add("$safeId.isEnabled = false")
            }
        }
    }

    private fun generateClickListeners(views: List<ViewBean>) {
        for (view in views) {
            if (!view.clickable || view.id.isBlank()) continue
            val safeId = safeKotlinId(view.id)
            val listenerCode = buildString {
                append("private fun setupClickListener${clickListeners.size}() {\n")
                append("    $safeId.setOnClickListener {\n")
                append("        // TODO: Handle click on ${view.name}\n")
                append("    }\n")
                append("}")
            }
            clickListeners.add(listenerCode)
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────

    private fun reset() {
        imports.clear()
        fieldDeclarations.clear()
        initStatements.clear()
        clickListeners.clear()
        lifecycleMethods.clear()
    }

    /** Convert a resource id like "button1" to a valid Kotlin identifier. */
    private fun safeKotlinId(id: String): String {
        if (id.first().isDigit()) return "_$id"
        return id.replace(Regex("[^a-zA-Z0-9_]"), "_")
    }

    private fun escapeKotlin(text: String): String = text
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("$", "\\$")
}
