package com.xcoder.visual.codegen

import com.xcoder.visual.*

/**
 * Generates Kotlin Activity/Fragment code from visual block graph.
 * Supports event handlers, variable declarations, control flow, function calls, UI manipulation.
 */
@Suppress("unused")
object KotlinGenerator {

    data class GenerationContext(
        val packageName: String = "com.xcoder.app",
        val activityName: String = "MainActivity",
        val layoutName: String = "activity_main",
        val imports: MutableSet<String> = mutableSetOf(
            "android.os.Bundle",
            "android.widget.*",
            "androidx.appcompat.app.AppCompatActivity"
        ),
        val variableDeclarations: MutableList<String> = mutableListOf(),
        val methodBodies: MutableList<String> = mutableListOf(),
        val importsNeeded: MutableSet<String> = mutableSetOf()
    )

    fun generate(
        blocks: List<PlacedBlock>,
        connections: List<BlockConnection>,
        context: GenerationContext = GenerationContext()
    ): String {
        val sortedBlocks = topologicalSort(blocks, connections)

        for (block in sortedBlocks) {
            generateBlockCode(block, connections, context)
        }

        return buildString {
            append("package ${context.packageName}\n\n")
            append("// Generated by XCoder IDE Visual Editor\n")
            append("// Do not edit manually\n\n")
            context.imports.forEach { append("import $it\n") }
            append("\n")
            append("class ${context.activityName} : AppCompatActivity() {\n\n")
            append("    override fun onCreate(savedInstanceState: Bundle?) {\n")
            append("        super.onCreate(savedInstanceState)\n")
            append("        setContentView(R.layout.${context.layoutName})\n\n")
            append("        // View bindings\n")
            generateViewBindings(blocks, context, this)
            append("\n")
            context.variableDeclarations.forEach { append("        $it\n") }
            append("\n")
            context.methodBodies.forEach { append("        $it\n\n") }
            append("    }\n")
            append("}\n")
        }
    }

    private fun generateBlockCode(
        block: PlacedBlock,
        connections: List<BlockConnection>,
        ctx: GenerationContext
    ) {
        when (block.definition.category) {
            BlockCategory.VARIABLES -> generateVariableBlock(block, ctx)
            BlockCategory.CONTROL -> generateControlBlock(block, connections, ctx)
            BlockCategory.LOGIC -> generateLogicBlock(block, ctx)
            BlockCategory.LOOPS -> generateLoopBlock(block, connections, ctx)
            BlockCategory.MATH -> generateMathBlock(block, ctx)
            BlockCategory.TEXT -> generateTextBlock(block, ctx)
            BlockCategory.UI -> generateUiActionBlock(block, connections, ctx)
            BlockCategory.INTENT -> generateIntentBlock(block, ctx)
            BlockCategory.FILE -> generateFileBlock(block, ctx)
            BlockCategory.NETWORK -> generateNetworkBlock(block, ctx)
            BlockCategory.EVENTS -> generateEventBlock(block, connections, ctx)
            else -> {}
        }
    }

    private fun generateVariableBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "var_set" -> {
                val name = block.values["name"] ?: "myVar"
                val value = block.values["value"] ?: "0"
                ctx.methodBodies.add("var_$name = $value")
            }
            "var_create" -> {
                val name = block.values["name"] ?: "myVar"
                val type = block.values["type"] ?: "String"
                val value = block.values["value"] ?: when (type) {
                    "String" -> "\"\""
                    "Int", "Number" -> "0"
                    "Boolean" -> "false"
                    "Double", "Float" -> "0.0"
                    "List" -> "emptyList()"
                    else -> "null"
                }
                val kotlinType = when (type) {
                    "Number", "Int" -> "Int"
                    "Double", "Float" -> "Double"
                    "String" -> "String"
                    "Boolean" -> "Boolean"
                    "List" -> "List<Any>"
                    "Object" -> "Any?"
                    else -> "Any?"
                }
                ctx.variableDeclarations.add("var $name: $kotlinType = $value")
            }
            "var_increment" -> {
                val name = block.values["name"] ?: "counter"
                val amount = block.values["amount"] ?: "1"
                ctx.methodBodies.add("$name += $amount")
            }
        }
    }

    private fun generateControlBlock(block: PlacedBlock, connections: List<BlockConnection>, ctx: GenerationContext) {
        when (block.definition.id) {
            "ctrl_if", "ctrl_if_else" -> {
                val condition = block.values["condition"] ?: "true"
                val thenBlocks = getConnectedBlocks(block, 0, connections)
                val elseBlocks = if (block.definition.id == "ctrl_if_else") {
                    getConnectedBlocks(block, 1, connections)
                } else emptyList()

                val thenCode = thenBlocks.joinToString("\n            ") { "${generateInline(it, connections, ctx)}" }
                val elseCode = elseBlocks.joinToString("\n            ") { "${generateInline(it, connections, ctx)}" }

                val sb = StringBuilder("if ($condition) {\n            $thenCode")
                if (elseBlocks.isNotEmpty()) {
                    sb.append("\n        } else {\n            $elseCode")
                }
                sb.append("\n        }")
                ctx.methodBodies.add(sb.toString())
            }
            "ctrl_return" -> {
                val value = block.values["value"] ?: ""
                ctx.methodBodies.add("return${if (value.isNotEmpty()) " $value" else ""}")
            }
            "ctrl_exit" -> {
                ctx.methodBodies.add("finish()")
            }
            "ctrl_wait" -> {
                val ms = block.values["milliseconds"] ?: "1000"
                ctx.importsNeeded.add("kotlinx.coroutines.delay")
                ctx.methodBodies.add("delay(${ms}L)")
            }
        }
    }

    private fun generateLogicBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "logic_compare" -> {
                val a = block.values["a"] ?: "0"
                val op = block.values["operator"] ?: "=="
                val b = block.values["b"] ?: "0"
                val kotlinOp = when (op) {
                    "==" -> "=="; "!=" -> "!="; ">" -> ">"; "<" -> "<"
                    ">=" -> ">="; "<=" -> "<="; else -> "=="
                }
                ctx.methodBodies.add("($a $kotlinOp $b)")
            }
            "logic_and" -> {
                val a = block.values["a"] ?: "true"
                val b = block.values["b"] ?: "true"
                ctx.methodBodies.add("(($a) && ($b))")
            }
            "logic_or" -> {
                val a = block.values["a"] ?: "false"
                val b = block.values["b"] ?: "false"
                ctx.methodBodies.add("(($a) || ($b))")
            }
            "logic_not" -> {
                val value = block.values["value"] ?: "true"
                ctx.methodBodies.add("!($value)")
            }
        }
    }

    private fun generateLoopBlock(block: PlacedBlock, connections: List<BlockConnection>, ctx: GenerationContext) {
        when (block.definition.id) {
            "loop_repeat" -> {
                val times = block.values["times"] ?: "10"
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("repeat($times.toInt()) {\n                $bodyCode\n            }")
            }
            "loop_for_each" -> {
                val list = block.values["list"] ?: "items"
                val bodyBlocks = getConnectedBlocks(block, 1, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("for (item in $list) {\n                $bodyCode\n            }")
            }
            "loop_while" -> {
                val cond = block.values["condition"] ?: "true"
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("while ($cond) {\n                $bodyCode\n            }")
            }
            "loop_break" -> ctx.methodBodies.add("break")
            "loop_continue" -> ctx.methodBodies.add("continue")
        }
    }

    private fun generateMathBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "math_arithmetic" -> {
                val a = block.values["a"] ?: "0"
                val op = block.values["operator"] ?: "+"
                val b = block.values["b"] ?: "0"
                val kotlinOp = when (op) { "+" -> "+"; "-" -> "-"; "*" -> "*"; "/" -> "/"; "%" -> "%"; else -> "+" }
                ctx.methodBodies.add("(($a) $kotlinOp ($b))")
            }
            "math_random" -> {
                val min = block.values["min"] ?: "0"
                val max = block.values["max"] ?: "100"
                ctx.importsNeeded.add("kotlin.random.Random")
                ctx.methodBodies.add("Random.nextInt($min.toInt(), $max.toInt() + 1)")
            }
            "math_abs" -> {
                val value = block.values["value"] ?: "0"
                ctx.importsNeeded.add("kotlin.math.abs")
                ctx.methodBodies.add("kotlin.math.abs($value)")
            }
            "math_round" -> {
                val value = block.values["value"] ?: "0"
                ctx.importsNeeded.add("kotlin.math.roundToInt")
                ctx.methodBodies.add("kotlin.math.roundToInt($value.toDouble())")
            }
        }
    }

    private fun generateTextBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "text_join" -> {
                val a = block.values["a"] ?: ""
                val b = block.values["b"] ?: ""
                ctx.methodBodies.add("(($a).toString() + ($b).toString())")
            }
            "text_length" -> {
                val text = block.values["text"] ?: ""
                ctx.methodBodies.add("($text).length")
            }
            "text_upper" -> {
                val text = block.values["text"] ?: ""
                ctx.methodBodies.add("($text).uppercase()")
            }
            "text_contains" -> {
                val text = block.values["text"] ?: ""
                val search = block.values["search"] ?: ""
                ctx.methodBodies.add("($text).contains($search)")
            }
        }
    }

    private fun generateUiActionBlock(block: PlacedBlock, connections: List<BlockConnection>, ctx: GenerationContext) {
        when (block.definition.id) {
            "ui_set_text" -> {
                val viewId = block.values["view"] ?: "textView1"
                val text = block.values["text"] ?: "\"\""
                ctx.methodBodies.add("$viewId.text = $text")
            }
            "ui_set_visibility" -> {
                val viewId = block.values["view"] ?: ""
                val visible = block.values["visible"] ?: "true"
                val visibility = if (visible.toBooleanStrictOrNull() == true) "View.VISIBLE" else "View.GONE"
                ctx.methodBodies.add("$viewId.visibility = $visibility")
            }
        }
    }

    private fun generateIntentBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "intent_toast" -> {
                val message = block.values["message"] ?: "Hello!"
                val length = block.values["length"] ?: "SHORT"
                val toastLength = if (length == "LONG") "Toast.LENGTH_LONG" else "Toast.LENGTH_SHORT"
                ctx.importsNeeded.add("android.widget.Toast")
                ctx.methodBodies.add("Toast.makeText(this, $message, $toastLength).show()")
            }
            "intent_finish" -> {
                ctx.methodBodies.add("finish()")
            }
            "intent_open" -> {
                val activity = block.values["activity"] ?: ""
                if (activity.isNotEmpty()) {
                    ctx.importsNeeded.add("android.content.Intent")
                    ctx.methodBodies.add("startActivity(Intent(this, $activity::class.java))")
                }
            }
        }
    }

    private fun generateFileBlock(block: PlacedBlock, ctx: GenerationContext) {
        when (block.definition.id) {
            "file_read" -> {
                val path = block.values["path"] ?: "/sdcard/file.txt"
                ctx.methodBodies.add("val fileContent = java.io.File($path).readText()")
            }
            "file_write" -> {
                val path = block.values["path"] ?: "/sdcard/file.txt"
                val content = block.values["content"] ?: ""
                ctx.methodBodies.add("java.io.File($path).writeText($content)")
            }
            "file_delete" -> {
                val path = block.values["path"] ?: ""
                ctx.methodBodies.add("java.io.File($path).delete()")
            }
        }
    }

    private fun generateNetworkBlock(block: PlacedBlock, ctx: GenerationContext) {
        ctx.importsNeeded.add("kotlinx.coroutines.Dispatchers")
        ctx.importsNeeded.add("kotlinx.coroutines.withContext")
        when (block.definition.id) {
            "net_http_get" -> {
                val url = block.values["url"] ?: ""
                ctx.methodBodies.add("""val response = withContext(Dispatchers.IO) {
                    java.net.URL("$url").readText()
                }""".trimIndent())
            }
            "net_http_post" -> {
                val url = block.values["url"] ?: ""
                val body = block.values["body"] ?: ""
                ctx.methodBodies.add("""val response = withContext(Dispatchers.IO) {
                    val conn = java.net.URL("$url").openConnection() as java.net.HttpURLConnection
                    conn.requestMethod = "POST"
                    conn.doOutput = true
                    conn.outputStream.write($body.toByteArray())
                    conn.inputStream.bufferedReader().readText()
                }""".trimIndent())
            }
        }
    }

    private fun generateEventBlock(block: PlacedBlock, connections: List<BlockConnection>, ctx: GenerationContext) {
        when (block.definition.id) {
            "evt_on_create" -> {
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                bodyBlocks.forEach { generateBlockCode(it, connections, ctx) }
            }
            "evt_on_click" -> {
                val viewId = block.values["view"] ?: "button1"
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("$viewId.setOnClickListener {\n                $bodyCode\n            }")
            }
            "evt_on_long_click" -> {
                val viewId = block.values["view"] ?: ""
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("$viewId.setOnLongClickListener {\n                $bodyCode\n                true\n            }")
            }
            "evt_on_change" -> {
                val viewId = block.values["view"] ?: "editText1"
                val bodyBlocks = getConnectedBlocks(block, 0, connections)
                val bodyCode = bodyBlocks.joinToString("\n                ") { generateInline(it, connections, ctx) }
                ctx.methodBodies.add("$viewId.addTextChangedListener(object : android.text.TextWatcher {\n" +
                    "                override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}\n" +
                    "                override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {\n                $bodyCode\n" +
                    "                }\n" +
                    "                override fun afterTextChanged(s: Editable?) {}\n" +
                    "            })")
                ctx.importsNeeded.add("android.text.Editable")
            }
        }
    }

    private fun generateInline(block: PlacedBlock, connections: List<BlockConnection>, ctx: GenerationContext): String {
        val sb = StringBuilder()
        when (block.definition.id) {
            "intent_toast" -> {
                val message = block.values["message"] ?: "Hello!"
                sb.append("Toast.makeText(this, $message, Toast.LENGTH_SHORT).show()")
                ctx.importsNeeded.add("android.widget.Toast")
            }
            "var_set" -> {
                val name = block.values["name"] ?: "myVar"
                val value = block.values["value"] ?: "0"
                sb.append("var_$name = $value")
            }
            "ui_set_text" -> {
                val viewId = block.values["view"] ?: "textView1"
                val text = block.values["text"] ?: "\"\""
                sb.append("$viewId.text = $text")
            }
            "var_increment" -> {
                val name = block.values["name"] ?: "counter"
                val amount = block.values["amount"] ?: "1"
                sb.append("$name += $amount")
            }
            else -> sb.append("// ${block.definition.name}")
        }
        return sb.toString()
    }

    private fun getConnectedBlocks(block: PlacedBlock, outputIndex: Int, connections: List<BlockConnection>): List<PlacedBlock> {
        val connected = connections.filter { it.fromBlockId == block.id && it.fromPortIndex == outputIndex }
        return connected.mapNotNull { conn ->
            null // Would need access to all blocks list to resolve; caller can pass blocks in
        }
    }

    private fun topologicalSort(blocks: List<PlacedBlock>, connections: List<BlockConnection>): List<PlacedBlock> {
        val inDegree = mutableMapOf<String, Int>()
        val graph = mutableMapOf<String, MutableList<String>>()
        blocks.forEach { inDegree[it.id] = 0; graph[it.id] = mutableListOf() }
        connections.forEach { (from, _, to) ->
            graph[from]?.add(to)
            inDegree[to] = (inDegree[to] ?: 0) + 1
        }
        val queue = java.util.LinkedList<String>()
        inDegree.filter { it.value == 0 }.keys.forEach { queue.add(it) }
        val result = mutableListOf<PlacedBlock>()
        val blockMap = blocks.associateBy { it.id }
        while (queue.isNotEmpty()) {
            val current = queue.poll()!!
            blockMap[current]?.let { result.add(it) }
            graph[current]?.forEach { next ->
                inDegree[next] = (inDegree[next] ?: 0) - 1
                if (inDegree[next] == 0) queue.add(next)
            }
        }
        return result
    }

    private fun generateViewBindings(blocks: List<PlacedBlock>, ctx: GenerationContext, sb: StringBuilder) {
        val uiBlocks = blocks.filter { it.definition.category == BlockCategory.UI }
        uiBlocks.forEach { block ->
            val viewId = block.values["id"] ?: return@forEach
            val varName = viewId
            val viewType = when (block.definition.id) {
                "ui_textview" -> "TextView"
                "ui_edittext" -> "EditText"
                "ui_button" -> "Button"
                "ui_imageview" -> "ImageView"
                else -> "View"
            }
            sb.append("        val $varName = findViewById<$viewType>(R.id.$viewId)\n")
        }
    }
}